# Generated by Django 4.1.7 on 2023-03-30 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(unique=True)),
                ('access_token', models.TextField(editable=False)),
                ('hostdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_api.hostdomain')),
            ],
        ),
    ]
