# Generated by Django 4.1.7 on 2023-03-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytoken',
            name='api_key',
            field=models.TextField(unique=True),
        ),
    ]
